# The root directory containing your Lexical files.
# You can use an absolute path or a relative path.
# Example: "C:/Users/YourUser/Documents/Notes"
# Example: "/home/youruser/notes"

content_directory: '/home/arkar/notes'

undotree_dir: '/home/arkar/notes/.history'

default_llm_model: 'qwen_2_5_0_5b_instruct'
