[[permission]]
identifier = "scope-user"
description = "Allow listing and reading user files."
commands.allow = [
    "read_file",
    "read",
    "open",
    "read_text_file",
    "read_text_file_lines",
    "read_text_file_lines_next",
    "write",
    "create_file",
    "create_directory",
    "list_directory",
    "get_file_info",
    "set_file_info",
    "copy",
    "move",
    "delete"
]

[[scope.allow]]
path = "@home"
[[scope.allow]]
path = "@home/*"
